apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-bdrd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-bdrd
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-bdrd
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-bdrd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-bdrd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-jcfo-tenant/appstudio/dc-metro-map-bdrd@sha256:fa21bf8d360783fe3e63f1f13df80a861f9c1d81cf17dd26bbd046b9d6c4df95
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
