apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-bdrd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-jcfo-tenant/appstudio/dc-metro-map-bdrd@sha256:fa21bf8d360783fe3e63f1f13df80a861f9c1d81cf17dd26bbd046b9d6c4df95
        name: my-nodejs
        resources: {}
status: {}
